# Generated by Django 5.0.3 on 2025-06-17 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledetails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiledetails',
            options={'verbose_name_plural': 'Profile Details'},
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='learning_preference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='preferred_learning_style',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='student_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
