# Generated by Django 5.2.1 on 2025-07-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledetails', '0002_alter_profiledetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiledetails',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Profile Details'},
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='about',
            field=models.TextField(blank=True, help_text='A brief description about the user'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='background',
            field=models.TextField(blank=True, help_text='Educational and professional background'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='learning_preference',
            field=models.CharField(blank=True, help_text='Additional learning preferences or notes', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='preferred_learning_style',
            field=models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading_writing', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic')], help_text='Preferred learning style from VARK model', max_length=20),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='student_type',
            field=models.CharField(blank=True, help_text='Type of student (e.g., high school, college, professional)', max_length=100),
        ),
    ]
