# Generated by Django 5.2.1 on 2025-07-05 06:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledetails', '0003_alter_profiledetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='learning_goals',
            field=models.JSONField(blank=True, default=list, help_text='Stores learning goals as an array of objects'),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='skill_levels',
            field=models.JSONField(blank=True, default=dict, help_text='Stores skill assessments in format {category: level}'),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='strengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="List of user's strengths", size=None),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='weaknesses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Areas for improvement', size=None),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='about',
            field=models.TextField(blank=True, help_text='A brief description about the user', null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='background',
            field=models.TextField(blank=True, help_text='Educational and professional background', null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='learning_preference',
            field=models.TextField(blank=True, help_text='Additional learning preferences or notes', null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='preferred_learning_style',
            field=models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading_writing', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic')], help_text='Preferred learning style from VARK model', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='student_type',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('student', 'Student'), ('professional', 'Professional'), ('career_changer', 'Career Changer'), ('hobbyist', 'Hobbyist')], help_text='Type of student', max_length=20, null=True),
        ),
    ]
