# Generated by Django 5.2.4 on 2025-08-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authent", "0002_alter_user_options_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_external_id",
            field=models.CharField(
                blank=True,
                help_text="External ID used for SPOC portal integration",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
