# Generated by Django 5.2.4 on 2025-08-04 05:51

import courses.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionoption",
            options={},
        ),
        migrations.RemoveField(
            model_name="course",
            name="thumbnail_url",
        ),
        migrations.RemoveField(
            model_name="module",
            name="image_url",
        ),
        migrations.AddField(
            model_name="course",
            name="average_rating",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(default="English", max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="learning_outcomes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="course",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="courses_enrolled", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=courses.models.course_thumbnail_path
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="total_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="module",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                default=0, help_text="Duration in minutes"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=courses.models.module_image_path
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="module",
            name="objectives",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True, help_text="Explanation of the correct answer"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.PositiveIntegerField(
                default=1, help_text="Points awarded for correct answer"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "Single Choice"),
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("short_answer", "Short Answer"),
                    ("essay", "Essay"),
                ],
                default="single_choice",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="feedback",
            field=models.TextField(
                blank=True, help_text="Feedback to show when this option is selected"
            ),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Maximum number of attempts allowed (0 for unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="require_passing",
            field=models.BooleanField(
                default=True,
                help_text="Whether passing this quiz is required to complete the module",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="show_correct_answers",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show correct answers after submission",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="time_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Time limit in minutes (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to=courses.models.section_media_path
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                default=0, help_text="Duration in minutes"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="external_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="section",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="section",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="passing_score",
            field=models.PositiveIntegerField(
                default=70,
                help_text="Passing percentage score (1-100)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("video", "Video"),
                    ("quiz", "Quiz"),
                    ("file", "File"),
                    ("link", "External Link"),
                    ("assignment", "Assignment"),
                ],
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="UserQuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("passed", models.BooleanField()),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_spent",
                    models.PositiveIntegerField(help_text="Time spent in seconds"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_attempts",
                        to="courses.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "get_latest_by": "completed_at",
            },
        ),
        migrations.CreateModel(
            name="UserQuizResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_response", models.TextField(blank=True)),
                ("is_correct", models.BooleanField()),
                ("points_earned", models.FloatField()),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="courses.userquizattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.question",
                    ),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(blank=True, to="courses.questionoption"),
                ),
            ],
            options={
                "ordering": ["question__order_number"],
            },
        ),
    ]
