# Generated by Django 5.2.1 on 2025-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_questionoption_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
