# Generated by Django 5.2.4 on 2025-12-06 20:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "requirements",
                    models.JSONField(
                        help_text="List of required skills and qualifications"
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                        ],
                        max_length=50,
                    ),
                ),
                ("apply_link", models.URLField(max_length=500)),
                ("posted_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("source", models.CharField(default="JSearch", max_length=100)),
                (
                    "raw_data",
                    models.JSONField(
                        default=dict, help_text="Raw data from the job API"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-posted_date"],
                "indexes": [
                    models.Index(
                        fields=["title", "company"], name="job_matchin_title_9db9a4_idx"
                    ),
                    models.Index(
                        fields=["job_type", "is_active"],
                        name="job_matchin_job_typ_1b4771_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobSearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_params",
                    models.JSONField(help_text="Parameters used for the job search"),
                ),
                ("total_results", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=dict,
                        help_text="Dictionary of skills with confidence scores",
                    ),
                ),
                (
                    "training_track",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "weak_points",
                    models.JSONField(
                        default=list, help_text="List of areas needing improvement"
                    ),
                ),
                (
                    "github_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "notion_integration_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "calendar_integration_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
            },
        ),
        migrations.CreateModel(
            name="JobMatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(
                        help_text="Matching percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "missing_skills",
                    models.JSONField(
                        default=list, help_text="List of skills the student is missing"
                    ),
                ),
                (
                    "readiness_days",
                    models.PositiveIntegerField(
                        help_text="Estimated days until job-ready"
                    ),
                ),
                (
                    "prep_plan",
                    models.JSONField(
                        default=dict, help_text="Generated preparation plan"
                    ),
                ),
                ("is_interested", models.BooleanField(default=False)),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("not_applied", "Not Applied"),
                            ("applied", "Applied"),
                            ("interviewing", "Interviewing"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                        ],
                        default="not_applied",
                        max_length=50,
                    ),
                ),
                (
                    "calendar_events",
                    models.JSONField(
                        default=list,
                        help_text="List of calendar event IDs for prep plan",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_matches",
                        to="job_matching.joblisting",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Match",
                "verbose_name_plural": "Job Matches",
                "ordering": ["-match_score", "-created_at"],
                "unique_together": {("student", "job")},
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "difficulty_level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Relative difficulty to learn (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "average_learning_hours",
                    models.PositiveIntegerField(
                        default=20, help_text="Average hours needed to learn this skill"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_skills",
                    models.ManyToManyField(blank=True, to="job_matching.skill"),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="job_matchin_name_a85ff7_idx"),
                    models.Index(
                        fields=["category"], name="job_matchin_categor_ff7ed8_idx"
                    ),
                ],
            },
        ),
    ]
