# Generated by Django 5.2.1 on 2025-07-05 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Whether the study plan is active')),
                ('preferred_time', models.TimeField(blank=True, help_text='Preferred time of day for study sessions', null=True)),
                ('reminder_email', models.BooleanField(default=True, help_text='Whether to send email reminders')),
                ('target_completion_date', models.DateField(blank=True, help_text='Target date to complete the study plan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Study Plan',
                'verbose_name_plural': 'User Study Plans',
            },
        ),
        migrations.CreateModel(
            name='StudyPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], help_text='Day of the week (0=Sunday, 1=Monday, etc.)')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_days', to='studyplan.userstudyplan')),
            ],
            options={
                'verbose_name': 'Study Plan Day',
                'verbose_name_plural': 'Study Plan Days',
                'ordering': ['day_of_week'],
                'unique_together': {('study_plan', 'day_of_week')},
            },
        ),
    ]
