# Generated by Django 5.2.1 on 2025-08-25 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_session_id", models.UUIDField(db_index=True)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("QR", "QR Code"),
                            ("CODE", "Manual Code"),
                            ("MANUAL", "Manual Entry"),
                        ],
                        default="QR",
                        max_length=10,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-marked_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "external_session_id"],
                        name="attendance__student_b1beb8_idx",
                    ),
                    models.Index(
                        fields=["marked_at"], name="attendance__marked__aa864c_idx"
                    ),
                ],
                "unique_together": {("external_session_id", "student")},
            },
        ),
    ]
