# Generated by Django 5.2.4 on 2025-08-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
    ]
