# Generated by Django 5.2.4 on 2025-08-30 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_populate_student_external_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": ["-marked_at"],
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
            },
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="last_sync_attempt",
            field=models.DateTimeField(
                blank=True, help_text="When the last sync attempt was made", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="source",
            field=models.CharField(
                default="EDUCATE",
                help_text="Source system where attendance was marked",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                    ("excused", "Excused"),
                ],
                default="present",
                help_text="Attendance status (present/absent/late/excused)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="student_external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External ID of the student (from SPOC server)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="sync_error",
            field=models.TextField(
                blank=True,
                help_text="Error message if sync with SPOC server failed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="synced_with_spoc",
            field=models.BooleanField(
                default=False,
                help_text="Whether the record was synced with the SPOC server",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="external_session_id",
            field=models.UUIDField(
                db_index=True, help_text="External session identifier from the QR code"
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the device that marked attendance",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="marked_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="When the attendance was marked",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="method",
            field=models.CharField(
                choices=[
                    ("QR", "QR Code"),
                    ("MANUAL", "Manual Entry"),
                    ("AUTO", "Automatic"),
                ],
                default="QR",
                help_text="How the attendance was marked",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="student",
            field=models.ForeignKey(
                help_text="Student who marked the attendance",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="user_agent",
            field=models.TextField(
                blank=True, help_text="User agent of the device that marked attendance"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["student_external_id"], name="attendance__student_fe4554_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["synced_with_spoc"], name="attendance__synced__7ee36c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["status"], name="attendance__status_741eb8_idx"),
        ),
    ]
